services:
  mysql:
    image: mysql:8
    container_name: sql-playground-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
